In [1]:
from shiny import App, ui, render, reactive
import pandas as pd
import matplotlib.pyplot as plt
from shinywidgets import output_widget, render_widget
import geopandas as gpd
from ipyleaflet import GeoJSON, Map, GeoData, LayersControl, basemaps, basemap_to_tiles, display, CircleMarker

In [5]:
work_sa2_data = pd.read_csv(r"data/2023-census-main-means-of-travel-to-work-by-statistical-area.csv")
study_sa2_data = pd.read_csv(r"data/2023-census-main-means-of-travel-to-education-by-statistical.csv")
path = r"data/statistical-area-2-2023-generalised-epsg4326.gpkg"

sa2shape2023 = gpd.read_file(path)

center_x = sa2shape2023.geometry.centroid.x.mean()
center_y = sa2shape2023.geometry.centroid.y.mean()

C:\Users\Jeff\AppData\Local\Temp\ipykernel_19872\1297851800.py:7: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  center_x = sa2shape2023.geometry.centroid.x.mean()
C:\Users\Jeff\AppData\Local\Temp\ipykernel_19872\1297851800.py:8: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  center_y = sa2shape2023.geometry.centroid.y.mean()

In [10]:
sa2shape2023

,SA22023_V1,SA22023__1,SA22023__2,LAND_AREA_,AREA_SQ_KM,Shape_Leng,geometry
0,100100,North Cape,North Cape,829.188012,829.188012,4.160392e+05,"MULTIPOLYGON (((173.15304 -34.75709, 173.15302..."
1,100200,Rangaunu Harbour,Rangaunu Harbour,274.004295,274.004295,1.490891e+05,"MULTIPOLYGON (((173.26482 -34.99699, 173.26501..."
2,100301,Inlets Far North District,Inlets Far North District,0.000000,623.222037,1.349364e+06,"MULTIPOLYGON (((173.28077 -35.27685, 173.28085..."
3,100400,Karikari Peninsula,Karikari Peninsula,174.440751,174.440751,1.401491e+05,"MULTIPOLYGON (((173.30152 -35.00198, 173.30124..."
4,100500,Tangonge,Tangonge,177.182117,177.182117,1.014669e+05,"MULTIPOLYGON (((173.24283 -35.06012, 173.25488..."
...,...,...,...,...,...,...,...
2390,400006,Campbell Island,Campbell Island,0.000000,0.000000,0.000000e+00,None
2391,400007,Oceanic Oil Rig Southland,Oceanic Oil Rig Southland,0.000000,0.000000,0.000000e+00,None
2392,400008,Oceanic Auckland Islands,Oceanic Auckland Islands,0.000000,0.000000,0.000000e+00,None
2393,400009,Auckland Islands,Auckland Islands,0.000000,0.000000,0.000000e+00,None
2394,400016,Ross Dependency,Ross Dependency,0.000000,0.000000,0.000000e+00,None

In [8]:
id_col = "SA2_2023_V1_00_Destination_NAME"
work_filtered = work_sa2_data[work_sa2_data[id_col] == "Addington East"]
work_total = work_filtered["work_2023_Total_stated"].sum()
work_filtered["commute_pct"] = (work_filtered["work_2023_Total_stated"] / work_total) * 100 if work_total > 0 else 0
study_filtered = study_sa2_data[study_sa2_data[id_col] == "Addington East"]
study_total = study_filtered["study_2023_Total_stated"].sum()
study_filtered["commute_pct"] = (study_filtered["study_2023_Total_stated"] / study_total) * 100 if study_total > 0 else 0

In [9]:
work_filtered

,SA2_2023_V1_00_Origin_CODE,SA2_2023_V1_00_Origin_NAME,SA2_2023_V1_00_Destination_CODE,SA2_2023_V1_00_Destination_NAME,work_2018_Work_at_home,work_2018_Drive_a_private_car_truck_or_van,work_2018_Drive_a_company_car_truck_or_van,work_2018_Passenger_in_a_car_truck_van_or_company_bus,work_2018_Public_bus,work_2018_Train,...,work_2023_Drive_a_company_car_truck_or_van,work_2023_Passenger_in_a_car_truck_van_or_company_bus,work_2023_Public_bus,work_2023_Train,work_2023_Bicycle,work_2023_Walk_or_jog,work_2023_Ferry,work_2023_Other,work_2023_Total_stated,commute_pct
57284,326100,Addington West,327400,Addington East,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,3.508772
57749,327400,Addington East,327400,Addington East,78,0,0,0,0,0,...,0,0,0,0,0,9,0,0,165,96.491228
57850,327600,Spreydon North,327400,Addington East,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.000000

In [15]:
sa2shape2023

,SA22023_V1,SA22023__1,SA22023__2,LAND_AREA_,AREA_SQ_KM,Shape_Leng,geometry
0,100100,North Cape,North Cape,829.188012,829.188012,4.160392e+05,"MULTIPOLYGON (((173.15304 -34.75709, 173.15302..."
1,100200,Rangaunu Harbour,Rangaunu Harbour,274.004295,274.004295,1.490891e+05,"MULTIPOLYGON (((173.26482 -34.99699, 173.26501..."
2,100301,Inlets Far North District,Inlets Far North District,0.000000,623.222037,1.349364e+06,"MULTIPOLYGON (((173.28077 -35.27685, 173.28085..."
3,100400,Karikari Peninsula,Karikari Peninsula,174.440751,174.440751,1.401491e+05,"MULTIPOLYGON (((173.30152 -35.00198, 173.30124..."
4,100500,Tangonge,Tangonge,177.182117,177.182117,1.014669e+05,"MULTIPOLYGON (((173.24283 -35.06012, 173.25488..."
...,...,...,...,...,...,...,...
2390,400006,Campbell Island,Campbell Island,0.000000,0.000000,0.000000e+00,None
2391,400007,Oceanic Oil Rig Southland,Oceanic Oil Rig Southland,0.000000,0.000000,0.000000e+00,None
2392,400008,Oceanic Auckland Islands,Oceanic Auckland Islands,0.000000,0.000000,0.000000e+00,None
2393,400009,Auckland Islands,Auckland Islands,0.000000,0.000000,0.000000e+00,None
2394,400016,Ross Dependency,Ross Dependency,0.000000,0.000000,0.000000e+00,None

In [18]:
study_map_shapes = sa2shape2023.merge(study_filtered[["SA2_2023_V1_00_Origin_NAME", "commute_pct"]], 
                                        left_on="SA22023__1", 
                                        right_on="SA2_2023_V1_00_Origin_NAME")

In [ ]:
study_map_shapes

,SA22023_V1,SA22023__1,SA22023__2,LAND_AREA_,AREA_SQ_KM,Shape_Leng,geometry,SA2_2023_V1_00_Origin_NAME,commute_pct
0,326100,Addington West,Addington West,0.553383,0.553383,4345.619737,"MULTIPOLYGON (((172.60897 -43.54248, 172.60947...",Addington West,5.882353
1,327400,Addington East,Addington East,0.568030,0.568030,3922.515449,"MULTIPOLYGON (((172.61567 -43.54239, 172.61577...",Addington East,88.235294
2,327600,Spreydon North,Spreydon North,1.213793,1.213793,4684.409508,"MULTIPOLYGON (((172.62308 -43.54749, 172.62347...",Spreydon North,5.882353

: